import { Client, GuildChannel } from 'discord.js'
import { EmbedBuilder, SlashCommandBuilder } from '@discordjs/builders'
import { formattedTimestamp, CORN_ID } from './utils'
import { Feedback } from '../interfaces/Feedback'
import { UserReport } from 'src/interfaces/UserReport'
import { tourData } from '../data/tourdata'

export function addTourSubcommands(builder: SlashCommandBuilder) {
  const activeTours = tourData.filter(tour => tour.active)
  activeTours.forEach(tour => {
    const choices = tour.dates.map(date => ({ name: date.name, value: date.role }))

    builder.addSubcommand(subcommand =>
      subcommand
        .setName(tour.key)
        .setDescription(tour.description)
        .addStringOption(option =>
          option
            .setName('show')
            .setDescription(tour.description)
            .setRequired(true)
            .setChoices(...choices)
        )
    )
  })

  return builder
}

export async function submitFeedback(feedback: Feedback, client: Client) {
  const guild = await client.guilds.fetch(feedback.guildId)
  const channel = (await guild.channels.fetch(feedback.channelId)) as GuildChannel
  const corn = await client.users.fetch(CORN_ID)

  const cornbotFeedbackEmbed = new EmbedBuilder()
    .setColor(0xff0000)
    .setTitle('New Alert')
    .setDescription('Someone has submitted feedback.')
    .addFields(
      { name: 'Submitter', value: `<@${feedback.submitterId}>`, inline: true },
      { name: 'Comment', value: feedback.comment, inline: true },
      { name: 'Guild', value: guild.name, inline: true },
      { name: 'Submitter', value: channel.name, inline: true },
      { name: 'Timestamp', value: formattedTimestamp(), inline: true }
    )
    .setTimestamp()
    .setFooter({ text: 'Feedback submission generated by Cornbot from user action.' })

  await corn.send({ embeds: [cornbotFeedbackEmbed] })
  return feedback
}

export async function submitReport(report: UserReport, client: Client) {
  const guild = await client.guilds.fetch(report.guildId)
  const channel = await guild.channels.fetch(report.channelId)
  const corn = await client.users.fetch(CORN_ID)
  const reportEmbed = new EmbedBuilder()
    .addFields(
      { name: 'Reported Member', value: `<@${report.reportedUserId}>`, inline: true },
      { name: 'Reason', value: report.reason, inline: true },
      { name: 'Reported By', value: `<@${report.reportedById}>`, inline: true },
      { name: 'Guild', value: guild.name, inline: true },
      { name: 'Channel', value: channel?.name ?? 'Unknown', inline: true },
      { name: 'Timestamp', value: formattedTimestamp(), inline: true }
    )
    .setTimestamp()

  report.userSubmitted
    ? reportEmbed

        .setColor(0xff7500)
        .setTitle('New User Report')
        .setDescription('A new user report has been submitted.')
        .setFooter({ text: 'Report generated by Cornbot from user action.' })
    : reportEmbed

        .setColor(0xff0000)
        .setTitle('New Alert')
        .setDescription('Someone did a thing...')
        .setFooter({ text: 'Report autogenerated by Cornbot.' })

  await corn.send({ embeds: [reportEmbed] })
  return report
}
